### ISSUE TITLE
JSON containing __proto__ in places other than keys gets mangled

### ISSUE THREAD

**Issue by piperswe** [DaniAkash/no-pollution#2]
See RunKit notebook: https://runkit.com/zebmccorkle/5d7aafb26b1e55001aa0cff9

The following JSON string does not parse correctly:

```json
{
    "key": "__proto__"
}
```

It parses to:

```json
{
    "key": "__pollutants__"
}
```

**Comment by DaniAkash** [comment]
@piperswe I can get around this issue by using the following regex https://regex101.com/r/Q6ba6D/1/tests but do think it'll cause any other issues?

**Comment by piperswe** [comment]
I switched to ECMAScript regex mode on regex101 (https://regex101.com/r/Q6ba6D/3) and it complains that the regex isn't valid ECMAScript regex, additionally Firefox refuses to parse it.

**Comment by DaniAkash** [comment]
Thanks for the detailed unit tests. I have created a regex that now matches almost all your test cases https://regex101.com/r/8c6MLf/2/tests, but one question does prototype pollution happen with Unicode escaping?
